version: "3.9"

networks:
  dev:

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - nextjs
      - fastapi
    networks:
      - dev

  nextjs:
    build: ./bolzhau.ai-main
    container_name: nextjs
    restart: always
    environment:
      - NODE_ENV=production
    networks:
      - dev

  fastapi:
    build: ./backend
    container_name: fastapi
    restart: always
    ports:
      - "8000:8000"
    networks:
      - dev
